title: "Stewardship Mapping and Assessment Twin Cities"
url: "https://MSP-LTER.github.io"  # GitHub Pages URL
baseurl: "/mspstewmap"  # Subdirectory path
markdown: kramdown
theme: jekyll-theme-minimal  # Optional Jekyll theme

# Clearer permalink structure for pages
permalink: /:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
